name: Doxygen Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        # fetch all history for all tags and branches
        with:
          fetch-depth: 0

      # Install doxygen in the system
      - name: Doxygen install
        run: sudo apt-get install -y doxygen

      # Generate html files of the documentation with doxygen
      - name: Update docs
        run: doxygen ./Doxyfile

      # Move generated documentation files to gh-pages branch
      - name: Move and commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git rm -rf docs
          git mv doxygen docs
          git commit -m 'update documentation'
          git push
